- TeamBST/.gitignore
> gitignore 추가 완료 O

- TeamBST/src/main/java/com/itwillbs/controller/TicketingController.java
- TeamBST/src/main/java/com/itwillbs/persistence/Game_scheduleDAO.java
- TeamBST/src/main/java/com/itwillbs/persistence/Game_scheduleDAOImpl.java
- TeamBST/src/main/java/com/itwillbs/service/ScheduleService.java
- TeamBST/src/main/java/com/itwillbs/service/ScheduleServiceImpl.java
- TeamBST/src/main/resources/mappers/scheduleMapper.xml
- TeamBST/src/main/webapp/WEB-INF/views/ticketing/gameInfo.jsp
- TeamBST/target/classes/mappers/scheduleMapper.xml
> #20 조수영 완료

- TeamBST/src/main/java/com/itwillbs/controller/CommunityController.java
- TeamBST/src/main/java/com/itwillbs/domain/Post_boardDTO.java
- TeamBST/src/main/java/com/itwillbs/persistence/CommunityDAO.java
- TeamBST/src/main/java/com/itwillbs/persistence/CommunityDAOImpl.java
- TeamBST/src/main/java/com/itwillbs/service/CommunityService.java
- TeamBST/src/main/java/com/itwillbs/service/CommunityServiceImpl.java
- TeamBST/src/main/resources/mappers/CommunityMapper.xml
- TeamBST/src/main/webapp/WEB-INF/views/community/community.jsp
- TeamBST/src/main/webapp/WEB-INF/views/community/communityWrite.jsp
> 59 회원 거래 게시판 작성, 리스트 출력

- TeamBST/src/main/webapp/WEB-INF/views/main/team/dosan.jsp
- TeamBST/src/main/webapp/WEB-INF/views/main/team/hanhwa.jsp
- TeamBST/src/main/webapp/WEB-INF/views/main/team/kia.jsp
- TeamBST/src/main/webapp/WEB-INF/views/main/team/kiwoom.jsp
- TeamBST/src/main/webapp/WEB-INF/views/main/team/kt.jsp
- TeamBST/src/main/webapp/WEB-INF/views/main/team/lg.jsp
- TeamBST/src/main/webapp/WEB-INF/views/main/team/lotte.jsp
- TeamBST/src/main/webapp/WEB-INF/views/main/team/nc.jsp
- TeamBST/src/main/webapp/WEB-INF/views/main/team/samsung.jsp
- TeamBST/src/main/webapp/WEB-INF/views/main/team/ssg.jsp
- TeamBST/target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
> 모든 사이트 연결완료

- TeamBST/src/main/webapp/WEB-INF/views/ticketing/gameInfo.jsp
> 찐으로 모든 페이지 연결 완료

- TeamBST/java/com/itwillbs/controller/MypageController.java
- TeamBST/java/com/itwillbs/persistence/MypageDAO.java
- TeamBST/java/com/itwillbs/persistence/MypageDAOImpl.java
- TeamBST/java/com/itwillbs/service/MypageService.java
- TeamBST/java/com/itwillbs/service/MypageServiceImpl.java
- TeamBST/src/main/webapp/WEB-INF/views/mypage/deleteMember.jsp
> 마이페이지 - 회원탈퇴 로직 완료

- TeamBST/src/main/webapp/WEB-INF/views/admin/adminMemberTicket.jsp
> jsp 추가 되라 제발

- TeamBST/java/com/itwillbs/controller/AnnouncementController.java
- TeamBST/java/com/itwillbs/controller/CommunityController.java
- TeamBST/java/com/itwillbs/persistence/AnnouncementDAO.java
- TeamBST/java/com/itwillbs/persistence/AnnouncementDAOImpl.java
- TeamBST/java/com/itwillbs/persistence/CommunityDAO.java
- TeamBST/java/com/itwillbs/persistence/CommunityDAOImpl.java
- TeamBST/java/com/itwillbs/service/AnnouncementService.java
- TeamBST/java/com/itwillbs/service/AnnouncementServiceImpl.java
- TeamBST/java/com/itwillbs/service/CommunityService.java
- TeamBST/java/com/itwillbs/service/CommunityServiceImpl.java
- TeamBST/src/main/resources/mappers/AnnouncementMapper.xml
- TeamBST/src/main/resources/mappers/CommunityMapper.xml
- TeamBST/src/main/webapp/WEB-INF/views/announcement/announcement.jsp
- TeamBST/src/main/webapp/WEB-INF/views/announcement/announcementContent.jsp
- TeamBST/src/main/webapp/WEB-INF/views/announcement/bulletin.jsp
- TeamBST/src/main/webapp/WEB-INF/views/announcement/bulletinContent.jsp
- TeamBST/src/main/webapp/WEB-INF/views/community/community.jsp
- TeamBST/src/main/webapp/WEB-INF/views/community/communityContent.jsp
> #93 문의사항 본문 출력 완료

- TeamBST/java/com/itwillbs/controller/CommunityController.java
- TeamBST/java/com/itwillbs/persistence/CommunityDAO.java
- TeamBST/java/com/itwillbs/persistence/CommunityDAOImpl.java
- TeamBST/java/com/itwillbs/service/CommunityService.java
- TeamBST/java/com/itwillbs/service/CommunityServiceImpl.java
- TeamBST/src/main/resources/mappers/CommunityMapper.xml
- TeamBST/src/main/webapp/WEB-INF/views/community/community.jsp
- TeamBST/src/main/webapp/WEB-INF/views/community/communityContent.jsp
- TeamBST/src/main/webapp/WEB-INF/views/community/communityModify.jsp
- TeamBST/src/main/webapp/WEB-INF/views/community/communityWrite.jsp
> 거래 게시판 댓글 제외 마무리

- TeamBST/java/com/itwillbs/controller/AnnouncementController.java
- TeamBST/java/com/itwillbs/persistence/AnnouncementDAO.java
- TeamBST/java/com/itwillbs/persistence/AnnouncementDAOImpl.java
- TeamBST/java/com/itwillbs/service/AnnouncementService.java
- TeamBST/java/com/itwillbs/service/AnnouncementServiceImpl.java
- TeamBST/src/main/resources/mappers/AnnouncementMapper.xml
- TeamBST/src/main/webapp/WEB-INF/views/announcement/bulletinContent.jsp
- TeamBST/src/main/webapp/WEB-INF/views/announcement/bulletinModify.jsp
> 문의 게시판 수정 삭제 버튼 추가 완료

- TeamBST/java/com/itwillbs/controller/AdminController.java
- TeamBST/java/com/itwillbs/controller/AnnouncementController.java
- TeamBST/java/com/itwillbs/controller/CommunityController.java
- TeamBST/java/com/itwillbs/domain/Post_boardDTO.java
- TeamBST/java/com/itwillbs/persistence/AdminDAO.java
- TeamBST/java/com/itwillbs/persistence/AdminDAOImpl.java
- TeamBST/java/com/itwillbs/persistence/AnnouncementDAO.java
- TeamBST/java/com/itwillbs/persistence/AnnouncementDAOImpl.java
- TeamBST/java/com/itwillbs/persistence/CommunityDAO.java
- TeamBST/java/com/itwillbs/persistence/CommunityDAOImpl.java
- TeamBST/java/com/itwillbs/service/AdminService.java
- TeamBST/java/com/itwillbs/service/AdminServiceImpl.java
- TeamBST/java/com/itwillbs/service/AnnouncementService.java
- TeamBST/java/com/itwillbs/service/AnnouncementServiceImpl.java
- TeamBST/java/com/itwillbs/service/CommunityService.java
- TeamBST/java/com/itwillbs/service/CommunityServiceImpl.java
- TeamBST/src/main/resources/mappers/AnnouncementMapper.xml
- TeamBST/src/main/resources/mappers/CommunityMapper.xml
- TeamBST/src/main/resources/mappers/adminMapper.xml
- TeamBST/src/main/webapp/WEB-INF/views/admin/adminBulletin.jsp
- TeamBST/src/main/webapp/WEB-INF/views/admin/adminNotice.jsp
- TeamBST/src/main/webapp/WEB-INF/views/admin/adminbulletinContent.jsp
- TeamBST/src/main/webapp/WEB-INF/views/announcement/bulletinContent.jsp
- TeamBST/src/main/webapp/WEB-INF/views/community/community.jsp
- TeamBST/src/main/webapp/WEB-INF/views/mypage/mywrite.jsp
- TeamBST/target/classes/mappers/adminMapper.xml
> #118- 모든 게시글 조회수 처리 완료

- TeamBST/java/com/itwillbs/controller/AdminController.java
- TeamBST/java/com/itwillbs/controller/LoginController.java
- TeamBST/java/com/itwillbs/domain/AdminDTO.java
- TeamBST/src/main/webapp/WEB-INF/views/include/adminheader.jsp
> 관리자 로그인 로직 수정

- TeamBST/java/com/itwillbs/controller/AdminController.java
- TeamBST/java/com/itwillbs/controller/AnnouncementController.java
- TeamBST/java/com/itwillbs/controller/TicketingController.java
- TeamBST/java/com/itwillbs/domain/Criteria.java
- TeamBST/java/com/itwillbs/domain/PageDTO.java
- TeamBST/java/com/itwillbs/persistence/AdminDAO.java
- TeamBST/java/com/itwillbs/persistence/AdminDAOImpl.java
- TeamBST/java/com/itwillbs/persistence/AnnouncementDAO.java
- TeamBST/java/com/itwillbs/persistence/AnnouncementDAOImpl.java
- TeamBST/java/com/itwillbs/service/AdminService.java
- TeamBST/java/com/itwillbs/service/AdminServiceImpl.java
- TeamBST/java/com/itwillbs/service/AnnouncementService.java
- TeamBST/java/com/itwillbs/service/AnnouncementServiceImpl.java
- TeamBST/src/main/resources/mappers/AnnouncementMapper.xml
- TeamBST/src/main/resources/mappers/adminMapper.xml
- TeamBST/src/main/webapp/WEB-INF/views/admin/adminBulletin.jsp
- TeamBST/src/main/webapp/WEB-INF/views/admin/adminGeneralMember.jsp
- TeamBST/src/main/webapp/WEB-INF/views/admin/adminNotice.jsp
- TeamBST/src/main/webapp/WEB-INF/views/admin/adminSchedule.jsp
- TeamBST/src/main/webapp/WEB-INF/views/admin/adminWithdrawMember.jsp
- TeamBST/src/main/webapp/WEB-INF/views/announcement/announcement.jsp
- TeamBST/src/main/webapp/WEB-INF/views/announcement/bulletin.jsp
- TeamBST/target/classes/mappers/adminMapper.xml
> 127     모든 게시판 페이징 처리

- TeamBST/java/com/itwillbs/controller/AdminController.java
- TeamBST/java/com/itwillbs/controller/MypageController.java
- TeamBST/java/com/itwillbs/persistence/AdminDAO.java
- TeamBST/java/com/itwillbs/persistence/AdminDAOImpl.java
- TeamBST/java/com/itwillbs/service/AdminService.java
- TeamBST/java/com/itwillbs/service/AdminServiceImpl.java
- TeamBST/src/main/resources/mappers/adminMapper.xml
- TeamBST/src/main/webapp/WEB-INF/views/admin/admin.jsp
- TeamBST/src/main/webapp/WEB-INF/views/admin/adminDeleteMember.jsp
- TeamBST/src/main/webapp/WEB-INF/views/admin/adminUpdateForm.jsp
- TeamBST/src/main/webapp/WEB-INF/views/include/adminheader.jsp
- TeamBST/src/main/webapp/WEB-INF/views/mypage/mypage.jsp
- TeamBST/target/classes/mappers/adminMapper.xml
> #132-관리자 본인정보 수정/탈퇴 완료

- TeamBST/java/com/itwillbs/controller/AdminController.java
- TeamBST/java/com/itwillbs/domain/PageDTO.java
- TeamBST/java/com/itwillbs/persistence/AdminDAO.java
- TeamBST/java/com/itwillbs/persistence/AdminDAOImpl.java
- TeamBST/java/com/itwillbs/persistence/MemberDAO.java
- TeamBST/java/com/itwillbs/service/AdminService.java
- TeamBST/java/com/itwillbs/service/AdminServiceImpl.java
- TeamBST/src/main/resources/mappers/adminMapper.xml
- TeamBST/src/main/resources/mappers/memberMapper.xml
- TeamBST/src/main/webapp/WEB-INF/views/admin/adminMemberTicket.jsp
- TeamBST/src/main/webapp/WEB-INF/views/include/header.jsp
- TeamBST/target/classes/mappers/adminMapper.xml
- TeamBST/target/classes/mappers/memberMapper.xml
> 135 파라미터 2개 넘겨야하는 페이징 처리

- TeamBST/java/com/itwillbs/controller/AdminLoginController.java
- TeamBST/java/com/itwillbs/controller/CommunityController.java
- TeamBST/java/com/itwillbs/controller/LoginController.java
- TeamBST/java/com/itwillbs/persistence/CommunityDAO.java
- TeamBST/java/com/itwillbs/persistence/CommunityDAOImpl.java
- TeamBST/java/com/itwillbs/service/CommunityService.java
- TeamBST/java/com/itwillbs/service/CommunityServiceImpl.java
- TeamBST/src/main/resources/mappers/CommunityMapper.xml
- TeamBST/src/main/resources/mappers/adminMapper.xml
- TeamBST/src/main/webapp/WEB-INF/views/announcement/announcementContent.jsp
- TeamBST/src/main/webapp/WEB-INF/views/announcement/bulletinContent.jsp
- TeamBST/src/main/webapp/WEB-INF/views/announcement/bulletinWrite.jsp
- TeamBST/src/main/webapp/WEB-INF/views/community/communityContent.jsp
- TeamBST/src/main/webapp/WEB-INF/views/mypage/mywrite.jsp
- TeamBST/target/classes/mappers/adminMapper.xml
> my게시글 클릭시 글내용 보는 것 제외 마무리

- TeamBST/java/com/itwillbs/controller/AnnouncementController.java
- TeamBST/java/com/itwillbs/persistence/AnnouncementDAO.java
- TeamBST/java/com/itwillbs/persistence/AnnouncementDAOImpl.java
- TeamBST/java/com/itwillbs/service/AnnouncementService.java
- TeamBST/java/com/itwillbs/service/AnnouncementServiceImpl.java
- TeamBST/src/main/resources/mappers/AnnouncementMapper.xml
- TeamBST/src/main/webapp/WEB-INF/views/announcement/bulletinContent.jsp
> 회원기준 답변출력 완료

- TeamBST/java/com/itwillbs/controller/AnnouncementController.java
- TeamBST/src/main/webapp/WEB-INF/views/announcement/bulletin.jsp
- TeamBST/src/main/webapp/WEB-INF/views/announcement/bulletinContent.jsp
> 비공개글 접근 제한 완료

- TeamBST/java/com/itwillbs/controller/MypageController.java
- TeamBST/java/com/itwillbs/controller/TicketingController.java
- TeamBST/java/com/itwillbs/persistence/MypageDAO.java
- TeamBST/java/com/itwillbs/persistence/MypageDAOImpl.java
- TeamBST/java/com/itwillbs/service/MypageService.java
- TeamBST/java/com/itwillbs/service/MypageServiceImpl.java
- TeamBST/src/main/resources/mappers/mypageMapper.xml
- TeamBST/src/main/webapp/WEB-INF/views/mypage/updateForm.jsp
- TeamBST/src/main/webapp/WEB-INF/views/ticketing/gameInfo.jsp
- TeamBST/target/classes/mappers/mypageMapper.xml
> 일반회원 어느정도 수정 완료

- TeamBST/java/com/itwillbs/controller/TicketingController.java
- TeamBST/src/main/webapp/WEB-INF/views/include/header.jsp
- TeamBST/src/main/webapp/WEB-INF/views/main/main.jsp
- TeamBST/src/main/webapp/WEB-INF/views/ticketing/ticketing.jsp
> 햄버거 버튼 / 메인페이지 구장 선택 오류 해결

- TeamBST/java/com/itwillbs/controller/AdminController.java
- TeamBST/java/com/itwillbs/controller/AnnouncementController.java
- TeamBST/java/com/itwillbs/controller/CommunityController.java
- TeamBST/java/com/itwillbs/persistence/AnnouncementDAO.java
- TeamBST/java/com/itwillbs/persistence/AnnouncementDAOImpl.java
- TeamBST/java/com/itwillbs/service/AnnouncementService.java
- TeamBST/java/com/itwillbs/service/AnnouncementServiceImpl.java
- TeamBST/src/main/webapp/WEB-INF/views/admin/adminNoticeContent.jsp
- TeamBST/src/main/webapp/WEB-INF/views/announcement/announcementContent.jsp
> 조회수 - 새로고침 로직 수정

- TeamBST/java/com/itwillbs/controller/AdminController.java
- TeamBST/src/main/webapp/WEB-INF/views/admin/adminNoticeContent.jsp
- TeamBST/src/main/webapp/WEB-INF/views/announcement/bulletinContent.jsp
- TeamBST/src/main/webapp/WEB-INF/views/community/communityContent.jsp
- TeamBST/src/main/webapp/WEB-INF/views/include/adminheader.jsp
> 게시글 삭제시 팝업창 띄우기

- TeamBST/src/main/resources/mappers/AnnouncementMapper.xml
- TeamBST/src/main/resources/mappers/adminMapper.xml
- TeamBST/src/main/webapp/WEB-INF/views/admin/adminNotice.jsp
- TeamBST/target/classes/mappers/adminMapper.xml
> 페이징 처리 수정완료

- TeamBST/java/com/itwillbs/controller/AnnouncementController.java
- TeamBST/java/com/itwillbs/controller/CommunityController.java
- TeamBST/java/com/itwillbs/controller/LoginController.java
- TeamBST/java/com/itwillbs/controller/TicketingController.java
- TeamBST/src/main/resources/mappers/AnnouncementMapper.xml
- TeamBST/src/main/webapp/WEB-INF/views/login/loginPage.jsp
로그아웃 상태에서 글작성/수정/댓글달기 -> 로그인 -> 해당 페이지로 이동
> 로그아웃 상태에서 글작성/수정/댓글달기 -> 로그인 -> 해당 페이지로 이동

- TeamBST/java/com/itwillbs/controller/AdminLoginController.java
- TeamBST/java/com/itwillbs/controller/LoginController.java
- TeamBST/java/com/itwillbs/persistence/AdminLoginDAO.java
- TeamBST/java/com/itwillbs/persistence/AdminLoginDAOImpl.java
- TeamBST/java/com/itwillbs/service/AdminLoginService.java
- TeamBST/java/com/itwillbs/service/AdminLoginServiceImpl.java
- TeamBST/src/main/resources/mappers/adminLoginMapper.xml
- TeamBST/src/main/webapp/WEB-INF/views/login/AdminLoginPage.jsp
- TeamBST/src/main/webapp/WEB-INF/views/login/AdminSignupPage.jsp
- TeamBST/src/main/webapp/WEB-INF/views/login/findId_result.jsp
- TeamBST/src/main/webapp/WEB-INF/views/login/loginPage.jsp
- TeamBST/src/main/webapp/WEB-INF/views/login/signupPage.jsp
- TeamBST/src/main/webapp/resources/css/adminLogin.css
- TeamBST/src/main/webapp/resources/css/adminSignup.css
- TeamBST/src/main/webapp/resources/css/login.css
- TeamBST/src/main/webapp/resources/css/signup.css
- TeamBST/src/main/webapp/resources/js/adminSignup.js
- TeamBST/src/main/webapp/resources/js/login_script.js
- TeamBST/src/main/webapp/resources/js/signup_script.js
로그인, 로그아웃(회원, 관리자) css 수정 완료
테스트까지 오류없이 통과
> 165 로그인, 로그아웃 css 수정

- TeamBST/src/main/webapp/WEB-INF/views/ticketing/displaySeats.jsp
- TeamBST/src/main/webapp/WEB-INF/views/ticketing/payment.jsp
- TeamBST/src/main/webapp/WEB-INF/views/ticketing/reservation.jsp
- TeamBST/src/main/webapp/WEB-INF/views/ticketing/stadium.jsp
- TeamBST/src/main/webapp/resources/css/displaySeats.css
- TeamBST/src/main/webapp/resources/css/index.css
- TeamBST/src/main/webapp/resources/css/payment.css
- TeamBST/src/main/webapp/resources/css/reservation.css
> 171 결제창 css

- TeamBST/java/com/itwillbs/controller/AdminController.java
- TeamBST/java/com/itwillbs/persistence/AdminDAO.java
- TeamBST/java/com/itwillbs/persistence/AdminDAOImpl.java
- TeamBST/java/com/itwillbs/service/AdminService.java
- TeamBST/java/com/itwillbs/service/AdminServiceImpl.java
- TeamBST/src/main/resources/mappers/adminMapper.xml
- TeamBST/src/main/webapp/WEB-INF/views/admin/adminUpdateForm.jsp
- TeamBST/src/main/webapp/WEB-INF/views/admin/adminbulletinContent.jsp
- TeamBST/target/classes/mappers/adminMapper.xml
> 관리자 - 문의게시판 - 내 답변 삭제 기능 완료
